# Generated by Django 4.2.4 on 2023-12-08 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='introduction',
            field=models.CharField(default=None, max_length=500),
        ),
    ]
