# Generated by Django 4.2.4 on 2023-12-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant', '0002_family_introduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='img_path',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
